version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "cinemaDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build: ./web/
    command: bash -c "python manage.py makemigrations --merge && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
