# Generated by Django 4.0.4 on 2022-07-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='releaseDate',
        ),
        migrations.AddField(
            model_name='film',
            name='from_torrent',
            field=models.BooleanField(default=True, verbose_name='Загрузка с торрента'),
        ),
        migrations.AddField(
            model_name='film',
            name='imagePath',
            field=models.TextField(default=None, verbose_name='Путь до постера'),
        ),
        migrations.AddField(
            model_name='film',
            name='magnet',
            field=models.TextField(default=None, verbose_name='Магнет ссылка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='torrentCinema.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
    ]
