# Generated by Django 4.0.4 on 2022-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0003_alter_film_imagepath_alter_film_magnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imagePath',
            field=models.TextField(null=True, verbose_name='Путь до постера'),
        ),
        migrations.AlterField(
            model_name='film',
            name='magnet',
            field=models.TextField(null=True, verbose_name='Магнет ссылка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
