# Generated by Django 4.0.4 on 2022-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0004_alter_film_imagepath_alter_film_magnet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imagePath',
        ),
        migrations.RemoveField(
            model_name='film',
            name='magnet',
        ),
        migrations.AddField(
            model_name='film',
            name='releaseDate',
            field=models.DateField(null=True, verbose_name='Дата Публикации'),
        ),
        migrations.AlterField(
            model_name='film',
            name='from_torrent',
            field=models.BooleanField(default=True, null=True, verbose_name='Загрузка с торрента'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рэйтинг'),
        ),
    ]
