# Generated by Django 4.0.4 on 2022-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0005_remove_film_imagepath_remove_film_magnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imagePath',
            field=models.TextField(null=True, verbose_name='Путь до постера'),
        ),
        migrations.AddField(
            model_name='film',
            name='magnet',
            field=models.TextField(null=True, verbose_name='Магнет ссылка'),
        ),
    ]
