# Generated by Django 4.0.4 on 2022-07-05 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torrentCinema', '0006_film_imagepath_film_magnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Тело комментария')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torrentCinema.film', verbose_name='Ссылка на фильм')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на автора')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
