# Generated by Django 3.2.14 on 2022-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0006_film_imagepath_film_magnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='magnet',
            field=models.CharField(max_length=1024, null=True, verbose_name='Магнет ссылка'),
        ),
    ]
