# Generated by Django 3.2.14 on 2022-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0007_alter_film_magnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.BooleanField(default=True, verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='film',
            name='magnet',
            field=models.TextField(max_length=1024, null=True, verbose_name='Магнет ссылка'),
        ),
    ]
