# Generated by Django 4.0.4 on 2022-07-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0009_alter_film_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='maincategory',
        ),
    ]
