# Generated by Django 4.0.4 on 2022-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0009_alter_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='localPath',
            field=models.CharField(max_length=255, null=True, verbose_name='Локальный Путь'),
        ),
    ]
