# Generated by Django 3.2.14 on 2022-07-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0010_сomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='primary',
            field=models.BooleanField(default=False, null=True, verbose_name='По подписке'),
        ),
        migrations.AlterField(
            model_name='сomment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_film', to='torrentCinema.film', verbose_name='Ссылка на фильм'),
        ),
    ]
