# Generated by Django 4.0.6 on 2022-07-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0010_remove_category_maincategory'),
        ('torrentCinema', '0011_remove_film_localpath'),
    ]

    operations = [
    ]
