# Generated by Django 3.2.14 on 2022-07-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0012_merge_20220709_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.BooleanField(default=True, verbose_name='Главная категория'),
        ),
    ]
