# Generated by Django 3.2.14 on 2022-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0012_film_localpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='localVideo',
            field=models.ImageField(null=True, upload_to='video/', verbose_name='локальное видео'),
        ),
    ]
