# Generated by Django 3.2.14 on 2022-07-10 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentCinema', '0013_film_localvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='localPath',
        ),
        migrations.AlterField(
            model_name='film',
            name='imagePath',
            field=models.ImageField(null=True, upload_to='media/poster/', verbose_name='Путь до постера'),
        ),
        migrations.AlterField(
            model_name='film',
            name='localVideo',
            field=models.FileField(null=True, upload_to='media/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
